import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="flex bg-lime-100 p-4">
          <div className="relative px-4 pr-4">
            <Image src={"/checklist.png"} width={64} height={64} alt="logo" />
          </div>
          <div>
            <p className="text-3xl font-bold">TODO LIST</p>
            <p> Create Your List</p>
          </div>
        </h1>
        {children}
      </body>
    </html>
  );
}
